spring:
  application:
    name: aiservice
  data:
    mongodb:
      uri: mongodb://localhost:27017/aireponsebfit
      database: aireponsebfit
  kafka:
    bootstrap-server: localhost:9092
    consumer:
      group-id: activity-processor-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: zaid.patel.BFit.aiservice.Entity.Activity
        spring.json.trusted.packages: "*"

kafka:
  topic:
    name: activity-events

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8083

gemini:
  api:
    url: ${GEMINI_URL}
    key: ${GEMINI_KEY}